### ISSUE TITLE
What did I get it wrong？

### ISSUE THREAD

**Issue by Wpolymer** [bjeffr/mwd_prediction#1]
Hi  Jeffrey!
Thank you very much for sharing your code. I`m a outsider of python. I`m having some trouble as follow when I run your scripts . Could you tell me what I did wrong? 

(base) D:\02_SOFT\GitHub\mwd_prediction\scripts>python data_gen_1C.py
  0%|                                                                                            | 0/5 [00:00<?, ?it/s]'LP2R.exe' is not recognized as an internal or external command, operable program or batch file
  0%|                                                                                            | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\02_SOFT\GitHub\mwd_prediction\scripts\data_gen_1C.py", line 84, in <module>
    main()
  File "D:\02_SOFT\GitHub\mwd_prediction\scripts\data_gen_1C.py", line 63, in main
    with open('gtp.dat') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'gtp.dat'

(base) D:\02_SOFT\GitHub\mwd_prediction\scripts>

**Comment by bjeffr** [comment]
Hi, What exactly are you trying to do? This is code I wrote for a school project and it used an executable that the school developed which I can't publish. That's why the scripts don't work.

**Comment by Wpolymer** [comment]
Thank you for your reply! I`m trying to find some tools that can transfer my rheological test data(G' and G'') to MWD. But there is almost no such free software online. Once again, it reached a dead end. I thought, maybe there is no shortcut, I have to read your paper deeply and learn a bit about Python, datasets generator and so on. Your paper is great，taught me a lot.

**Comment by bjeffr** [comment]
For this technically you wouldn't need the executable if you have enough data to train the models yourself. If not you could reach out to the university for the tool we used. Their contacts are listed in the thesis.
